/**
 * Per-animal calibration offsets, added to compatibility (0–1 scale).
 * Generated by `npm run balance`; do not edit by hand. Animals missing
 * from this list use 0. Re-run the script after adding or changing animals.
 */
export const ANIMAL_BALANCE: Record<string, number> = {
  'shingleback-skink': -0.036,
  'giant-day-gecko': -0.014,
  'red-eyed-tree-frog': -0.013,
  'bald-eagle': -0.052,
  'harris-hawk': -0.105,
  'scarlet-macaw': -0.054,
  'crow': -0.053,
  'blue-jay': -0.065,
  'california-sea-lion': -0.023,
  'asian-elephant': -0.034,
  'tiger': -0.007,
  'canada-lynx': -0.011,
  'cheetah': -0.033,
  'serval': -0.021,
  'coyote': -0.076,
  'grey-wolf': -0.076,
  'painted-dog': -0.065,
  'fennec-fox': -0.1,
  'river-otter': -0.033,
  'stoat': -0.023,
  'orca': -0.039,
  'bottlenose-dolphin': -0.048,
  'humpback-whale': -0.015,
  'sailfish': -0.014,
  'giant-pacific-octopus': -0.024,
  'bumble-bee': -0.056,
  'leafcutter-ant': -0.015,
  'snow-leopard': -0.022,
  'raccoon': -0.019,
  'brown-bear': -0.032,
  'blacktip-reef-shark': -0.007,
  'white-rhino': -0.014,
  'hippopotamus': -0.037,
  'orangutan': -0.025,
  'ring-tailed-lemur': -0.07,
  'sperm-whale': -0.024,
  'asian-giant-hornet': -0.013
};
